language: ruby
rvm:
- 2.0.0
- 1.9.2
notifications:
  email: false
gemfile:
  - gemfiles/Gemfile.activesupport-3.x
  - gemfiles/Gemfile.activesupport-4.x
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.activesupport-4.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.activesupport-3.x
